bank_app/urls.py
from django.urls import path
from . import views


app_name = "bank_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('admin-dashboard', views.admin_page, name='admin_page'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('make_loan_request/', views.make_loan_request, name='make_loan_request'),
    path('review_loan_request', views.review_loan_request, name='review_loan_request'),
    path('make_account_request/', views.make_account_request, name='make_account_request'),
    path('make_transfer/', views.make_transfer, name='make_transfer'),
    path('add_customer/', views.add_customer, name='add_customer'),
    path('admin-dashboard/<int:id>/decline', views.decline_loan_request, name='decline_loan_request'),
    path('admin-dashboard/<int:id>/approve', views.approve_loan_request, name='approve_loan_request'),
    path('admin-dashboard/<int:id>/decline-account', views.decline_account_request, name='decline_account_request'),
    path('admin-dashboard/<int:id>/approve-account', views.approve_account_request, name='approve_account_request'),
    path('account-details/<int:id>', views.account_details, name='account_details'),
    path('customer_overview/', views.customer_overview, name='customer_overview'),
    path('search_customers/', views.search_customers, name='search_customers')
]

kea_bank_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/logout/', auth_views.logout_then_login, name='logout'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('', include('bank_app.urls'))
]

bank_app/forms.py
from django import forms
from .models import Customer, Account
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404


class LoanRequestForm(forms.Form):

    # Ensure loan_amount is positive

    loan_amount = forms.DecimalField(min_value=0)

    def clean_loan_amount(self):
        loan_amount = self.cleaned_data['loan_amount']
        if loan_amount < 0:
            raise forms.ValidationError("Please enter a positive loan amount.")
        return loan_amount


class AccountRequestForm(forms.Form):
    customer = forms.ModelChoiceField(queryset=Customer.objects.all(), widget=forms.HiddenInput())


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ["phone", "rank"]


class AccountModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return f'{obj.id} - {obj.title} ({obj.balance} DKK)'


class TransferForm(forms.Form):
    amount = forms.DecimalField(max_digits=25, decimal_places=2)
    debit_account = AccountModelChoiceField(queryset=Account.objects.all())
    debit_text = forms.CharField()
    credit_account = forms.IntegerField(label="Recipient account number:")
    credit_text = forms.CharField()

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        customer = Customer.objects.get(user=user)
        self.fields['debit_account'].queryset = Account.objects.filter(customer=customer, is_loan=False)

    def clean(self):
        cleaned_data = super().clean()
        amount = cleaned_data.get('amount')
        debit_account = cleaned_data.get('debit_account')
        credit_account_id = cleaned_data.get('credit_account')

        if amount and debit_account and amount > debit_account.balance:
            self.add_error('amount', 'Amount exceeds balance of selected account.')

        if credit_account_id:
            credit_account = get_object_or_404(Account, id=credit_account_id)
            cleaned_data['credit_account'] = credit_account

        return cleaned_data

bank_app/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.template.loader import render_to_string
from .models import Customer, LoanRequest, AccountRequest, Ledger, Account, ApprovedLoanRequests, ApprovedAccountRequests
from .forms import LoanRequestForm, AccountRequestForm, UserForm, CustomerForm, TransferForm
from django.db import IntegrityError, transaction
from secrets import token_urlsafe


@login_required
def index(request):
    if request.user.is_staff:
        return HttpResponseRedirect(reverse('bank_app:admin_page'))
    else:
        return HttpResponseRedirect(reverse('bank_app:dashboard'))


@login_required
def admin_page(request):
    users = User.objects.all()
    loan_requests = LoanRequest.objects.all()
    account_requests = AccountRequest.objects.all()
    approved_loan_requests = ApprovedLoanRequests.objects.all()
    accounts = Account.objects.all()
    context = {
        'accounts': accounts,
        'approved_loan_requests': approved_loan_requests,
        'users': users,
        'loan_requests': loan_requests,
        'account_requests': account_requests,
    }
    return render(request, 'bank_app/admin_page.html', context)


@login_required
def dashboard(request):
    customer = Customer.objects.get(user=request.user)
    rank = customer.rank
    loan_requests = LoanRequest.objects.filter(customer=customer)
    account_requests = AccountRequest.objects.filter(customer=customer)
    accounts = Account.objects.filter(customer=customer)
    context = {
        'accounts': accounts,
        'rank': rank,
        'loan_requests': loan_requests,
        'account_requests': account_requests,
    }

    return render(request, 'bank_app/dashboard.html', context)


@login_required
def make_loan_request(request):
    if request.method == 'POST':
        form = LoanRequestForm(request.POST)
        if form.is_valid():
            LoanRequest.objects.create(customer=request.user.customer, loan_amount=request.POST['loan_amount'])
            return HttpResponseRedirect(reverse('bank_app:dashboard'))
        else:
            form = LoanRequestForm()
            context = {
                'error': '* Please enter a positive loan ammount',
            }
            return render(request, 'bank_app/make_loan_request.html', context)
    return render(request, 'bank_app/make_loan_request.html')


@login_required
def make_account_request(request):
    customer = request.user.customer
    form = AccountRequestForm(initial={'customer': customer})
    if request.method == 'POST':
        form = AccountRequestForm(request.POST)
        if form.is_valid():
            customer = form.cleaned_data["customer"]
            try:
                AccountRequest.objects.create(customer=customer)
                return HttpResponseRedirect(reverse('bank_app:dashboard'))
            except IntegrityError:
                return IntegrityError
        else:
            return render(request, 'bank_app/make_account_request.html', {'form': form})
    else:
        return render(request, 'bank_app/make_account_request.html', {'form': form})


@login_required
@require_http_methods(['DELETE'])
def decline_loan_request(request, id):
    loan_request = get_object_or_404(LoanRequest, id=id)
    try:
        loan_request.delete()
        return HttpResponse("<button disabled>Declined</button>", content_type="text/html")
    except IntegrityError:
        return HttpResponse(status_code=500)


@login_required
@require_http_methods(['POST'])
def approve_loan_request(request, id):
    try:
        loan_request = get_object_or_404(LoanRequest, id=id)
        with transaction.atomic():
            loan_request.status = "approved"
            loan_request.save()
            # If customer has accout use transfer to that account, if not create an account
            if Account.objects.filter(customer=loan_request.customer).exists():
                customer_account = Account.objects.filter(customer=loan_request.customer).first()
            else:
                customer_account = Account.objects.create(customer=loan_request.customer, title="Account 1", is_loan=False)
            # create account for loan
            loan_i = Account.objects.filter(customer=loan_request.customer, is_loan=True).count() + 1
            loan_account = Account.objects.create(customer=loan_request.customer, title=f"Loan {loan_i}", is_loan=True)
            # add loan_requests to approved_loan_requests
            ApprovedLoanRequests.objects.create(
                loan_request=loan_request, account=loan_account, approved_by=request.user)
            # information for ledger
            amount = loan_request.loan_amount
            debit_account = loan_account
            debit_text = "Approved " + loan_account.title
            credit_account = customer_account
            credit_text = "Approved " + loan_account.title

            # create ledger
            Ledger.transfer(amount, debit_account, debit_text, credit_account, credit_text)

            return HttpResponse("<button disabled>Approved</button>", content_type="text/html")
    except IntegrityError:
        return HttpResponse(status_code=500)


@login_required
@require_http_methods(['DELETE'])
def decline_account_request(request, id):
    account_request = get_object_or_404(AccountRequest, id=id)
    try:
        account_request.delete()
        return HttpResponse("<button disabled>Declined</button>", content_type="text/html")
    except IntegrityError:
        return HttpResponse(status_code=500)


@login_required
@require_http_methods(['POST'])
def approve_account_request(request, id):
    try:
        account_request = get_object_or_404(AccountRequest, id=id)
        with transaction.atomic():
            account_request.status = "approved"
            account_request.save()

            # create account for account, and account for use
            account = Account.objects.create(customer=account_request.customer, title="Account")

            # add account_requests to approved_account_requests
            ApprovedAccountRequests.objects.create(account_request=account_request, account=account, approved_by=request.user)

            return HttpResponse("<button disabled>Approved</button>", content_type="text/html")
    except IntegrityError:
        return HttpResponse(status_code=500)


@login_required
def review_loan_request(request):

    loan_request = LoanRequest.objects.all()
    context = {
        'loan_request': loan_request
    }
    return render(request, 'bank_app/review_loan_request.html', context)


@login_required
def add_customer(request):
    if request.user.is_staff:
        user_form = UserForm()
        customer_form = CustomerForm()

        context = {
            'user_form': user_form,
            'customer_form': customer_form
        }

        if request.method == 'POST':
            user_form = UserForm(request.POST)
            customer_form = CustomerForm(request.POST)
            if user_form.is_valid() and customer_form.is_valid():
                username = user_form.cleaned_data["username"]
                first_name = user_form.cleaned_data["first_name"]
                last_name = user_form.cleaned_data["last_name"]
                email = user_form.cleaned_data["email"]
                password = token_urlsafe(16)
                phone = customer_form.cleaned_data["phone"]
                rank = customer_form.cleaned_data["rank"]
                try:
                    user = User.objects.create_user(
                        username=username,
                        password=password,
                        email=email,
                        first_name=first_name,
                        last_name=last_name
                    )
                    print(f'********** Username: {username} -- Password: {password}')
                    Customer.objects.create(user=user, rank=rank, phone=phone)
                    return admin_page(request)
                except IntegrityError:
                    context['error_msg'] = 'User could not be created, please try again'
                    return render(request, 'bank_app/add_customer.html', context)
            else:
                context["errors"] = user_form.errors
                return render(request, 'bank_app/add_customer.html', context)
        else:
            return render(request, 'bank_app/add_customer.html', context)
    else:
        return HttpResponseRedirect(reverse('login'))


@login_required
def customer_overview(request):
    if request.user.is_staff:
        customers = Customer.objects.all()
        context = {
            'customers': customers,
        }
        return render(request, 'bank_app/customer_overview.html', context)
    else:
        return HttpResponseRedirect(reverse('bank_app:dashboard'))


@login_required
def search_customers(request):
    assert request.user.is_staff, 'Customer user routing staff view.'
    search_term = request.GET['search']
    customers = Customer.objects.all()
    if len(search_term) == 0:
        customers = Customer.objects.all()
    else:
        customers = Customer.search(search_term)
    context = {
        'customers': customers,
    }
    rendered = render_to_string('bank_app/partials/search_customer_results.html', context)
    return HttpResponse(rendered)


@login_required
def account_details(request, id):
    customer = Customer.objects.get(user=request.user)
    account = get_object_or_404(Account, id=id, customer=customer)
    context = {
        'account': account
    }
    return render(request, 'bank_app/account_details.html', context)


@login_required
def make_transfer(request):
    if request.method == 'POST':
        form = TransferForm(request.POST, user=request.user)

bank_app/templates/bank_app/account_details.html
{% extends "base.html" %}

{% block main %}

<h1>Account details</h1>
<h2>{{account.title}}</h2>
<p>Account number: <strong>{{account.id}}</strong></p>
<p>Balance: <strong>{{account.balance}}</strong></p>
<table>
    <thead>
        <tr>
          <th>Amount</th>
          <th>New balance</th>
          <th>Message</th>
          <th>Date</th>
        </tr>
      </thead>
    <tbody>
    {% for i in account.movements %}
    <tr>
        <td>
          {% if i.amount > 0 %}
          +{{i.amount}}
          {% else %}
          {{i.amount}}
          {% endif %}
        </td>
        <td>
          {{i.balance_at_time}}
        </td>   
        <td>{{i.message}}</td>
        <td>{{i.transaction.datetime}}</td>  
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

bank_app/templates/bank_app/add_customer.html
{% extends "base.html" %}

{% block title %}<title>Add new customer</title>{% endblock %}

{% block main %}

<h1>Add a new customer</h1>

{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}
{% if errors %}
    <p>There were errors in the form:</p>
    {{ errors}}
{% endif %}

<form method="post">
    {% csrf_token %}
    <fieldset>
    {{ user_form.as_p }}
    </fieldset>
    <fieldset>
    {{ customer_form}}
    </fieldset>
    <input type="submit" value="Add customer">
</form>

{% endblock %}

bank_app/templates/bank_app/admin_loan_requests.html
{% extends "admin_page.html" %}
{% block loan_requests %}

    <ul id="loan_requests">  {% for loan_request in loan_requests %}
        {% if loan_request.status == "not reviewed" %}
    <li>Customer: {{ loan_request.customer.full_name}}
            id : {{loan_request.id}}
            <br>
            {% if loan_request.status == "approved" %}
            Status: Approved
            {% endif %}
            {% if loan_request.status == "declined" %}
            Status: Declined
            {% endif %}
            {% if loan_request.status == "not reviewed" %}
            status: Not Reviewed
            {% endif %}
            <br>
        Amount: {{loan_request.loan_amount}}
        <br>
        Date: {{loan_request.created_at}}
        <br>

        <button
                hx-swap="outerHTML"
                hx-target="#loan_requests"
                hx-confirm="Are you sure you want to approve this loan?"
            hx-patch="{% url 'bank_app:approve_loan_request' loan_request.id %}"
            hx-trigger="click"
            value="approved"
            name="approve_loan_request">
            Approve
        </button>
        <button
                hx-swap="delete"
                hx-target="#loan_requests"
                hx-confirm="Are you sure you want to delete this loan request?"
            name="decline_loan_request"
            hx-trigger="click"
            hx-delete="{% url 'bank_app:decline_loan_request' loan_request.id %}"
            value="declined"
            >
            Decline
        </button>
        <button onClick="window.location.href='/review_loan_request/{{loan_request.customer.pk}}';">Review</button>
       </li>
       {% endif %}
        {% endfor %}
    </ul>

{% endblock %}

bank_app/templates/bank_app/admin_page.html
{% extends "base.html" %}

{% block title %}<title>Bank admin</title>{% endblock %}

{% block main %}

<h1>Welcome {{ user }}!</h1>

<h2>Users</h2>
<ul>
    {% for user in users %}
    {% if user != request.user %}
    <li>{{ user.username }}</li>
    {% endif %}
    {% endfor %}
</ul>

<h2>Loan Requests</h2>

<!-- {% block loan_requests %}-->
<!--  {% endblock loan_requests %}-->

<ul id="loan_requests">

    {% for loan_request in loan_requests %}
    {% if loan_request.status == "not reviewed" %}
    <li id="loan_request_{{ loan_request.id }}">Customer: {{ loan_request.customer.full_name}}
        id : {{loan_request.id}}
        <br>
        {% if loan_request.status == "approved" %}
        Status: Approved
        {% endif %}
        {% if loan_request.status == "declined" %}
        Status: Declined
        {% endif %}
        {% if loan_request.status == "not reviewed" %}
        status: Not Reviewed
        {% endif %}

        <br>
        Amount: {{loan_request.loan_amount}}
        <br>
        Date: {{loan_request.created_at}}
        <br>
        <div class="button-container">
            <button hx-target="closest .button-container" hx-swap="innerHTML"
                _="on htmx:confirm(issueRequest)
                halt the event
                call Swal.fire({title: 'Approve loan', text:'Are you sure you want to approve the loan?'})
                if result.isConfirmed issueRequest()
                end
                on htmx:responseError(issueRequest)
                halt the event
                call Swal.fire({title: 'Error', text:'There was an error, and the loan could not be approved. Please try again'})"
                hx-post="{% url 'bank_app:approve_loan_request' loan_request.id %}"
                hx-trigger="click"
                value="approved"
                name="approve_loan_request">
                Approve
            </button>
            <button
                hx-target="closest .button-container"
                hx-swap="innerHTML"
                _="on htmx:confirm(issueRequest)
                halt the event
                call Swal.fire({title: 'Decline loan', text:'Are you sure you want to decline the loan?'})
                if result.isConfirmed issueRequest()
                end
                on htmx:responseError(issueRequest)
                halt the event
                call Swal.fire({title: 'Error', text:'There was an error, and the loan could not be declined. Please try again'})"
                hx-delete="{% url 'bank_app:decline_loan_request' loan_request.id %}"
                name="decline_loan_request"
                hx-trigger="click"
                value="declined"
                >
                Decline
            </button>
        </div>
    </li>
    {% endif %}
    {% endfor %}
</ul>

<hr>

<h2>Account Requests</h2>

<ul id="account_requests">

    {% for account_request in account_requests %}
    {% if account_request.status == "not reviewed" %}
    <li id="account_request_{{ account_request.id }}">Customer: {{ account_request.customer.full_name}}
        id : {{account_request.id}}
        <br>
        {% if account_request.status == "approved" %}
        Status: Approved
        {% endif %}
        {% if account_request.status == "declined" %}
        Status: Declined
        {% endif %}
        {% if account_request.status == "not reviewed" %}
        status: Not Reviewed
        {% endif %}

        <br>
        Amount: {{account_request.account_amount}}
        <br>
        Date: {{account_request.created_at}}
        <br>
        <div class="button-container">
            <button hx-target="closest .button-container" hx-swap="innerHTML"
                _="on htmx:confirm(issueRequest)
               halt the event
                call Swal.fire({title: 'Approve account', text:'Are you sure you want to approve the account?'})
                if result.isConfirmed issueRequest()
                end
                on htmx:responseError(issueRequest)
                halt the event
                call Swal.fire({title: 'Error', text:'There was an error, and the account could not be approved. Please try again'})"
                hx-post="{% url 'bank_app:approve_account_request' account_request.id %}" hx-trigger="click"
                value="approved" name="approve_account_request">
                Approve
            </button>
            <button hx-target="closest .button-container" hx-swap="innerHTML"
                _="on htmx:confirm(issueRequest)
                halt the event
                call Swal.fire({title: 'Decline account', text:'Are you sure you want to decline the account?'})
                if result.isConfirmed issueRequest()
                end
                on htmx:responseError(issueRequest)
                halt the event
                call Swal.fire({title: 'Error', text:'There was an error, and the account could not be declined. Please try again'})" hx-trigger="click"
                hx-delete="{% url 'bank_app:decline_account_request' account_request.id %}" value="declined">
                Decline
            </button>
        </div>
    </li>
    {% endif %}
    {% endfor %}
</ul>

<hr>

<h2>Approved loans</h2>
<ul id="approved_loan_requests">
    {% for approved_loan_request in approved_loan_requests %}

    <li>
        amount: {{approved_loan_request.loan_request.loan_amount}}
        title: {{approved_loan_request.account.title}}
        customer: {{approved_loan_request.account.customer.full_name}}
        approved by:{{approved_loan_request.approved_by}}
    </li>

    {% endfor %}
</ul>

<h2>All Loans</h2>
<ul>
    {% for account in accounts %}
    {% if account.balance < 0 %} <li>customer name:{{account.customer.full_name}}
        title: {{account.title}}
        balance: {{account.balance}}

        </li>{% endif %}
        {% endfor %}
</ul>

<h2>All Accounts</h2>
<ul>
    {% for account in accounts %}
    {% if account.balance >= 0 %}

    <li>
        customer name:{{account.customer.full_name}}
        title: {{account.title}}
        balance: {{account.balance}}
    </li>{% endif %}
    {% endfor %}
</ul>
{% endblock %}

bank_app/templates/bank_app/approved_loan_requests.html
<ul id="approved_loan_requests">
    {% for approved_loan_request in approved_loan_requests %}
</ul>

bank_app/templates/bank_app/customer_overview.html
{% extends "base.html" %}

{% block title %}<title>Customers</title>{% endblock %}

{% block main %}

<h1>Customer overview</h1>
<div>
  <input
      type="search" 
      name="search" 
      class="form-control"
      placeholder="Search Users..." 
      hx-get="{% url 'bank_app:search_customers' %}" 
      hx-trigger="keyup changed delay:500ms" 
      hx-target="#search-results" 
      >
</div>

<hr>
<section>
    <table>
      <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Rank</th>
          <th>Accounts</th>
          <th>Loans</th>
          <th>Phone</th>
        </tr>
      </thead>
      <tbody id="search-results">
      {% include "bank_app/partials/search_customer_results.html" %}
      </tbody>
    </table>
</section>

{% endblock %}	

bank_app/templates/bank_app/dashboard.html
{% extends "base.html" %}

{% block title %}<title>{{ user.first_name }}'s Dashboard</title>{% endblock %}

{% block main %}

<section >
  <h1>Welcome {{ user.first_name }}!</h1>
  <p>Account rank: {{rank.name}} </p>
</section>
<section class="grid-2">
  <div>
    <h2>My accounts</h2>
    <table>
      <thead>
        <tr>
          <th>Number</th>
          <th>Name</th>
          <th class="align-right">Balance</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for account in accounts %}
        {% if account.is_loan == False %}
        <tr>
          <td>{{ account.id }}</td>
          <td>{{ account.title }}</td>
          <td class="align-right">{{ account.balance }} DKK</td>
          <td class="float-right" ><a href="/account-details/{{account.id}}">More</a></td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div>
    <h2>My loans</h2>
    <table>
      <thead>
        <tr>
          <th>Number</th>
          <th>Name</th>
          <th class="float-right">Balance</th>
        </tr>
      </thead>
      <tbody>
        {% for loan in accounts %}

        {% if loan.is_loan == True %}
        <tr>
          <td>{{loan.id }}</td>
          <td>{{loan.title}}</td>
          <td class="float-right">{{ loan.balance }} DKK</td>
        </tr>
        {% endif %}
        {% empty %}
        <p>You have no loans</p>
        <button><a href="{% url 'bank_app:make_loan_request' %}">Apply for a loan</a></button>
        {% endfor %}
      </tbody>
    </table>
  </div>
</section>
<br>
<hr>
<section class="grid-2">
  <div>
    <h2>Pending loan requests</h2>
    <table>
      <thead>
        <tr>
          <th>Loan Amount</th>
          <th>Currency</th>
        </tr>
      </thead>
      <tbody>
        {% for loan_request in loan_requests %}
        {% if loan_request.status == "not reviewed" %}

        <tr>
          <td>{{ loan_request.loan_amount }}</td>
          <td>DKK</td>
        </tr>
        {% endif %}
        {% empty %}
        <p>You have no pending loan requests</p>
        <button><a href="{% url 'bank_app:make_loan_request' %}">Apply for a loan</a></button>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div>
    <h2>Pending account requests </h2>
    <table>
      <thead>
        <tr>
          <th>Account name</th>
        </tr>
      </thead>
      <tbody>
        {% for account_request in account_requests %}
        <tr>
          <td>{{ account_request.id }}</td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
  </div>
</section>
{% endblock %}

bank_app/templates/bank_app/loan_request.html
{% extends 'base.html' %}

{% block main %}
    <h2>List of all loans:</h2>
    <ul>
    {% for loan in loans %}
        <li>Loan amount: {{ loan.loan_amount }}</li>
    {% empty %}
        <li>No loans found.</li>
    {% endfor %}
    </ul>

    <h2>List of approved loans:</h2>
    <ul>
    {% for loan in approved_loans %}
        <li>Loan amount: {{ loan.loan_amount }}</li>
    {% empty %}
        <li>No approved loans found.</li>
    {% endfor %}
    </ul>
{% endblock %}

bank_app/templates/bank_app/make_account_request.html
{% extends 'base.html' %}

{% block main %}
<h1>Request an Account</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

bank_app/templates/bank_app/make_loan_request.html
{% extends 'base.html' %}

{% block main %}
  <h1>Make a Loan Request</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <label for="loan_amount">Loan Amount:</label>
    <input type="number" id="loan_amount" name="loan_amount" required>
    <div> {{ error }} </div>
  </form>
{% endblock %}

bank_app/templates/bank_app/make_transfer.html
{% extends 'base.html' %}

{% block main %}
  <h1>Transfer money</h1>
  <blockquote> Here you can transfer money between your accounts, as well as pay off any outstanding loans you may have.</blockquote>

  <form method="post">
      {% csrf_token %}
      <fieldset>
          <legend>Debit Information:</legend>
          {{ form.amount.label_tag }}{{ form.amount }}
          {% for error in form.amount.errors %}
              <span class="error">{{ error }}</span>
          {% endfor %}
          <br>
          {{ form.debit_account.label_tag }} {{ form.debit_account }}
          {% for error in form.debit_account.errors %}
              <span class="error">{{ error }}</span>
          {% endfor %}
          <br>
          {{ form.debit_text.label_tag }} {{ form.debit_text }}
          {% for error in form.debit_text.errors %}
              <span class="error">{{ error }}</span>
          {% endfor %}
          <br>
      </fieldset>
      <br>
        <fieldset>
          <legend>Credit Information:</legend>
          {{ form.credit_account.label_tag }} {{ form.credit_account }}
          {% for error in form.credit_account.errors %}
              <span class="error">{{ error }}</span>
          {% endfor %}
          <br>
          {{ form.credit_text.label_tag }} {{ form.credit_text }}
          {% for error in form.credit_text.errors %}
              <span class="error">{{ error }}</span>
          {% endfor %}
          <br>
        </fieldset>
      <br>
      {% for error in form.non_field_errors %}
          <li>{{ error }}</li>
      {% endfor %}
      <input class="float-right" type="submit" value="Submit">
  </form>
{% endblock %}

bank_app/templates/bank_app/review_loan_request.html
{% extends 'base.html' %}

{% block main %}

<h2>Customer information</h2>

Customer:
accounts:
loan:

<h2>loan request</h2>
amount:
date:
status:

{{ loan_request }}

<br>
<button>Approve</button><button>Decline</button>

{% endblock %}