bank_app/urls.py
from django.urls import path
from . import views


app_name = "bank_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('admin-dashboard', views.admin_page, name='admin_page'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('make_loan_request/', views.make_loan_request, name='make_loan_request'),
    path('review_loan_request', views.review_loan_request, name='review_loan_request'),
    path('make_account_request/', views.make_account_request, name='make_account_request'),
    path('make_transfer/', views.make_transfer, name='make_transfer'),
    path('add_customer/', views.add_customer, name='add_customer'),
    path('admin-dashboard/<int:id>/decline', views.decline_loan_request, name='decline_loan_request'),
    path('admin-dashboard/<int:id>/approve', views.approve_loan_request, name='approve_loan_request'),
    path('admin-dashboard/<int:id>/decline-account', views.decline_account_request, name='decline_account_request'),
    path('admin-dashboard/<int:id>/approve-account', views.approve_account_request, name='approve_account_request'),
    path('account-details/<int:id>', views.account_details, name='account_details'),
    path('customer_overview/', views.customer_overview, name='customer_overview'),
    path('search_customers/', views.search_customers, name='search_customers')
]

kea_bank_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/logout/', auth_views.logout_then_login, name='logout'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('', include('bank_app.urls'))
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="robots" content="noindex, nofollow">
        <title>KEA Bank</title>
        <meta name="description" content="Student project Backend with Python and Django elective at KEA Schoold of Design and Technology">
        <meta name="keywords" content="student, project">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block title %}
        {% endblock %}
        {% load static %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css">
        <link rel="stylesheet" href="{% static 'css/general.css' %}" type="text/css">
    </head>
    <body hx-ext="multi-swap"
        hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        <header>
        <nav>
            {% if request.user.is_authenticated %}
                {% if request.user.is_staff %}
                <a href="{% url 'bank_app:admin_page' %}">Dashboard</a><span> &nbsp; &nbsp;</span>
                <a href="{% url 'bank_app:customer_overview' %}">Customers</a><span> &nbsp; &nbsp;</span>
                <a href="{% url 'bank_app:add_customer' %}">+ Add a customer</a><span> &nbsp; &nbsp;</span>
                {% else %}
                <a href="{% url 'bank_app:dashboard' %}">Home</a><span> &nbsp; &nbsp;</span>
                <a href="{% url 'bank_app:make_loan_request' %}">+ New Loan</a><span> &nbsp; &nbsp;</span>
                <a href="{% url 'bank_app:make_account_request' %}">+ New Account</a><span> &nbsp; &nbsp;</span>
                <a href="{% url 'bank_app:make_transfer' %}">Make Transfer</a><span> &nbsp; &nbsp;</span>
                {% endif %}
		        <a class="float-right" href="{% url 'logout' %}"><button>Logout</button></a>
            {% endif %}
        </nav>
        <br>
        </header>

        {% block main %}
        {% endblock main %}
    </body>
    <script src="https://unpkg.com/htmx.org@1.8.6" integrity="sha384-Bj8qm/6B+71E6FQSySofJOUjA/gq330vEqjFx9LakWybUySyI1IQHwPtbTU7bNwx" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/htmx.org/dist/ext/multi-swap.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://unpkg.com/hyperscript.org@0.9.8"></script>
</html>